## <a href='https://www.gnu.org/software/octave/'>GNU Octave </a>
<ul>
<li> A high-level interpreted language </li>
<li> primarily uses for numerical computations </li> 
<li> a tool of data visualization and manipulation </li> 
<li> Octave language is quite similar to Matlab </li> </ul>

## Basic Operations

In [1]:
5+7

ans =  12


In [2]:
6/4

ans =  1.5000


In [3]:
5-6

ans = -1


In [4]:
2^4

ans =  16


In [5]:
5*5


ans =  25


In [6]:
sin(5)

ans = -0.95892


In [7]:
cos(5)

ans =  0.28366


In [8]:
tan(pi)

ans =   -1.2246e-16


In [9]:
pi

ans =  3.1416


In [10]:
format long

In [11]:
pi

ans =  3.14159265358979


In [12]:
format short

In [13]:
exp(1)

ans =  2.7183


In [14]:
log(exp(1))

ans =  1


In [15]:
log10(10)

ans =  1


In [16]:
sinh(4)

ans =  27.290


In [17]:
tanh(3)

ans =  0.99505


In [18]:
x1 = sqrt(100^2 -60^2)
x1*15*(60^2 + x1^2)^(-1/2)

x1 =  80
ans =  12


# vector and matrix

In [19]:
% row vector
x=[1 2]

x =

   1   2



In [20]:
% column vector 
y=[3;4]

y =

   3
   4



In [21]:
% transpose
y'

ans =

   3   4



In [22]:
y=[3 4]

y =

   3   4



In [23]:
A=[1 2; 3 4]

A =

   1   2
   3   4



A*A and A^2 are same but A.^2 is different! A*A or A^2 are the multiplication of A with A; however, A.^2 is the component wise pultiplication.

In [24]:
A*A
A^2
A.^2

ans =

    7   10
   15   22

ans =

    7   10
   15   22

ans =

    1    4
    9   16



In [25]:
B = [5 6; 7 8]

B =

   5   6
   7   8



In [26]:
C=B^(-1)

C =

  -4.0000   3.0000
   3.5000  -2.5000



In [27]:
A*C

ans =

   3.00000  -2.00000
   2.00000  -1.00000



In [28]:
B*C

ans =

   1.00000   0.00000
   0.00000   1.00000



In [29]:
% component wise multiplication 
B.*C

ans =

  -20.000   18.000
   24.500  -20.000



In [30]:
inv(B)

ans =

  -4.0000   3.0000
   3.5000  -2.5000



In [31]:
% determinant
det(B)

ans = -2.0000


In [32]:
help eig

'eig' is a built-in function from the file libinterp/corefcn/eig.cc

 -- Built-in Function: LAMBDA = eig (A)
 -- Built-in Function: LAMBDA = eig (A, B)
 -- Built-in Function: [V, LAMBDA] = eig (A)
 -- Built-in Function: [V, LAMBDA] = eig (A, B)
     Compute the eigenvalues (and optionally the eigenvectors) of a
     matrix or a pair of matrices

     The algorithm used depends on whether there are one or two input
     matrices, if they are real or complex, and if they are symmetric
     (Hermitian if complex) or non-symmetric.

     The eigenvalues returned by 'eig' are not ordered.

     See also: eigs, svd.

Additional help for built-in functions and operators is
available in the online version of the manual.  Use the command
'doc <topic>' to search the manual index.

Help and information about Octave is also available on the WWW
at http://www.octave.org and via the help@octave.org
mailing list.


In [33]:
A=[1 2 3; 4 5 6; 7 8 98]

A =

    1    2    3
    4    5    6
    7    8   98



In [34]:
[eigvec, eigval] = eig(A)

eigvec =

  -0.031944  -0.812694  -0.329567
  -0.065196   0.582597  -0.938125
  -0.997361   0.010440   0.106334

eigval =

Diagonal Matrix

   98.74715          0          0
          0   -0.47228          0
          0          0    5.72513



$a_{1,1} \quad   a_{1,2}  \quad  a_{1,3}$

$a_{2,1} \quad   a_{2,2}  \quad  a_{2,3}$

$a_{3,1} \quad   a_{3,2}  \quad  a_{3,3}$

In [35]:
A(1:3,3)

ans =

    3
    6
   98



In [36]:
size(A)

ans =

   3   3



In [37]:
A=zeros(3)

A =

   0   0   0
   0   0   0
   0   0   0



In [38]:
A = eye(4)

A =

Diagonal Matrix

   1   0   0   0
   0   1   0   0
   0   0   1   0
   0   0   0   1



In [39]:
A=rand(4)

A =

   0.691284   0.458066   0.969734   0.981280
   0.523134   0.193470   0.780486   0.076756
   0.414799   0.367310   0.369840   0.400804
   0.431737   0.505204   0.080192   0.592407



Solve the linear system $Ax =b$.

In [40]:
A=[1 2 3; 3 3 4; 2 3 3];
b=[1; 1; 2];
x=A\b

x =

  -0.50000
   1.50000
  -0.50000



## more vectors

In [43]:
x = 1:5

x =

   1   2   3   4   5



In [44]:
x = 1:0.5:5

x =

 Columns 1 through 8:

    1.0000    1.5000    2.0000    2.5000    3.0000    3.5000    4.0000    4.5000

 Column 9:

    5.0000



In [45]:
length(x)

ans =  9


In [47]:
x = linspace(0,5,11)

x =

 Columns 1 through 8:

   0.00000   0.50000   1.00000   1.50000   2.00000   2.50000   3.00000   3.50000

 Columns 9 through 11:

   4.00000   4.50000   5.00000



In [50]:
index = find(x>2)

index =

    6    7    8    9   10   11



In [51]:
x(index)

ans =

   2.5000   3.0000   3.5000   4.0000   4.5000   5.0000



## run a script file 
For example plottest.m is an script file. We can run plottest.m by simply write plottest

In [42]:
%plot gnuplot
plottest